name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout branche
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
  
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish NuGet on version changed
      uses: rohith/publish-nuget@v2.2.1
      with:
        PROJECT_FILE_PATH: Pandatheque.AuthorizedAction.MediatR/Pandatheque.AuthorizedAction.MediatR.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
